name: Build Android AAB

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore file
        run: |
          echo "$UPLOAD_STORE_FILE_BASE64" | base64 -d > android/app/my-release-key.keystore
        env:
          UPLOAD_STORE_FILE_BASE64: ${{ secrets.UPLOAD_STORE_FILE_BASE64 }}

      - name: Set up Gradle properties for signing
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=android/app/my-release-key.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.UPLOAD_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.UPLOAD_STORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.UPLOAD_KEY_PASSWORD }}" >> android/gradle.properties

      - name: Build AAB
        working-directory: android
        run: ./gradlew bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
